# 罠07：「Excel」と称するファイルの中身が HTML

> **一行でいうと**
> ファイルの種類は、**拡張子でも、提供元の説明でもなく、中身で決まる**。
> そして、表の形は**仮定するのではなく、データから見つける**。

**この罠の危険度：★★★☆☆**
今回は**きちんとエラーで止まります**。その意味では良心的です。ただし、エラーメッセージが原因をまったく示さないので、素直に読むと迷子になります。

---

## 目次

1. [前回までのあらすじ](#1-前回までのあらすじ)
2. [BPSには2種類の表がある](#2-bpsには2種類の表がある)
3. [どちらの表か、URLから見分ける](#3-どちらの表かurlから見分ける)
4. [症状：「Excel」が開けない](#4-症状excelが開けない)
5. [中身を見る ── 何が入っていたか](#5-中身を見る--何が入っていたか)
6. [さらに良い発見：ダウンロードすら要らなかった](#6-さらに良い発見ダウンロードすら要らなかった)
7. [小さな罠：HTMLエンティティを戻す順序](#7-小さな罠htmlエンティティを戻す順序)
8. [ここからが本番 ── 表の形が毎回違う](#8-ここからが本番--表の形が毎回違う)
9. [対処：形を仮定せず、探す](#9-対処形を仮定せず探す)
10. [1つの表に、2つの指標が横に並んでいる](#10-1つの表に2つの指標が横に並んでいる)
11. [数値の書式と、州名の改行](#11-数値の書式と州名の改行)
12. [脚注が、州として混入する](#12-脚注が州として混入する)
13. [直ったことをどう確かめたか](#13-直ったことをどう確かめたか)
14. [あなたのAPIでも同じことが起きる](#14-あなたのapiでも同じことが起きる)
15. [チェックリスト](#15-チェックリスト)
16. [まとめ](#16-まとめ)
17. [付録A：コード全文](#付録aコード全文)
18. [付録B：よくある質問](#付録bよくある質問)

---

## 1. 前回までのあらすじ

ここまでの6本は、すべて**動的表**（数値をJSONで返してくれる表）の話でした。

- [罠01](01-silent-truncation.md)：カタログが500件で切れていた
- [罠02](02-bilingual-catalog.md)：英語で絞ると表が漏れた
- [罠03](03-year-parameter.md)：年の必須指定と3年上限
- [罠04](04-composite-key.md)：キーを組み立てる設計
- [罠05](05-derived-dimensions.md)：切り口を選ばないと合計が2倍
- [罠06](06-empty-rows.md)：行はあるが値が空

**ここまでで、動的表は安定して取れるようになりました。**

今回は、**もう一方の表**の話です。

---

## 2. BPSには2種類の表がある

BPS の統計表は、2つに分かれています。

| | 動的表（`var`） | 静的表（`statictable`） |
|---|---|---|
| 件数 | 1,816件 | 720件 |
| 数値の返り方 | **JSON** | **ファイル** |
| 年の指定 | できる | できない（表ごと固定） |
| 形 | 決まっている | **表ごとにバラバラ** |
| 扱いやすさ | ○ | △ |

動的表だけで済めばよかったのですが、**必要な指標が静的表にしかない**ことがありました。

この作業で静的表から取った指標は2つです。

- **カロリー・タンパク質の摂取量**（静的表 951）
- **都市人口比率**（静的表 1276）── [研究上いちばん重要な変数](README.md)

とくに後者は、先行する分析で唯一有意だった変数でした。**「静的表だから諦める」という選択肢はありません。**

---

## 3. どちらの表か、URLから見分ける

作業を始めてすぐ、小さな発見がありました。

BPS のウェブサイトで統計表を開くと、URLがこうなっています。

```
https://www.bps.go.id/id/statistics-table/2/MTg4NiMy/......html
                                            ~~~~~~~~
```

この `MTg4NiMy` の部分が何なのか、最初は分かりませんでした。ランダムな文字列に見えます。

しかし形（英数字＋末尾の `=`）から **base64** だと当たりをつけて戻してみると、

```
MTg4NiMy  →  1886#2
OTQ1IzE=  →  945#1
```

**「ID#種別」でした。**

| 種別 | 意味 |
|---|---|
| `#1` | 静的表（statictable） |
| `#2` | 動的表（var） |

つまり `1886#2` は「動的表の1886番」、`945#1` は「静的表の945番」です。

これが分かると、**ブラウザで見つけた表を、そのままAPIで叩けるようになります**。表を探すときはウェブサイトのほうが速いので、この対応付けは実務上とても効きました。

```r
#' BPS 統計表URLの base64 部分を "{id}#{type}" に戻す
#' @examples bps_decode_slug("MTg4NiMy")   # "1886#2"
bps_decode_slug <- function(s) {
  s <- gsub("=+$", "", s)
  pad <- (4 - nchar(s) %% 4) %% 4
  s <- paste0(s, strrep("=", pad))
  txt <- rawToChar(jsonlite::base64_dec(s))
  parts <- strsplit(txt, "#", fixed = TRUE)[[1]]
  list(
    id   = parts[1],
    type = if (length(parts) > 1) parts[2] else NA_character_,
    kind = if (length(parts) > 1 && parts[2] == "1") "statictable" else "var"
  )
}
```

**base64 の詰め物（パディング）を自分で足し直している**のは、URLに埋め込むとき末尾の `=` が落とされることがあるからです。落ちたまま戻そうとすると失敗します。

> **URL の中の意味不明な文字列は、base64 を疑う価値がある。**

---

## 4. 症状：「Excel」が開けない

さて本題です。

静的表の情報を API から取ると、`excel` というフィールドにファイルの URL が入っていました。名前のとおり Excel ファイルだと思って、素直にダウンロードして読みます。

```r
readxl::read_excel("out/table_951.xls")
```

**エラーになりました。**

```
Error: 
  filepath: out/table_951.xls
  libxls error: Unable to open file
```

「ファイルを開けません」。

### エラーが何も教えてくれない

このメッセージから分かるのは「開けなかった」ことだけです。考えられる原因はいくらでもあります。

- ダウンロードが途中で切れた？
- 認証が要る？
- ファイルが壊れている？
- 古い形式の `.xls` で、ライブラリが対応していない？
- そもそもファイルが空？

**エラーは出るが、原因は分からない。** [罠03](03-year-parameter.md) の `status: Error` と同じ状況です。

そして、[罠03](03-year-parameter.md) で学んだ対処が、そのまま使えます。

> **生のまま、中身を見る。**

---

## 5. 中身を見る ── 何が入っていたか

ダウンロードしたファイルの先頭を、テキストとして表示してみます。

```r
readLines("out/table_951.xls", n = 5)
```

出てきたのは、これでした。

```html
<table border="1">
<tr><td colspan="39">Daily Average Consumption of Calorie and Protein ...</td></tr>
<tr><td></td></tr>
<tr><td>Province</td><td>Calories (kkal)</td>...
```

**HTML でした。**

拡張子は `.xls`。API のフィールド名は `excel`。しかし**中身は HTML の `<table>`** です。

### なぜこうなるのか

これは BPS に限らず、**古い業務システムでよくある形**です。

Excel は、HTML の表を貼り付けると、そのまま表として開いてくれます。つまり「HTMLを出力して、拡張子を `.xls` にしておけば、ユーザーが Excel で開ける」わけです。**本物の Excel 形式を書き出すプログラムを作らなくて済みます。**

利用者（人間）にとっては、これで何の問題もありません。ダブルクリックすれば Excel が開きます。

問題が起きるのは、**プログラムから読むとき**だけです。`readxl` は本物の Excel 形式を期待しているので、HTML を渡されると「開けない」と言います。

**誰も悪くありません。** 想定していた使い方が違うだけです。

### 教訓

> **ファイルの種類は、拡張子でも、提供元の説明でもなく、中身で決まる。**

ファイルが読めないときは、**まず先頭数行をテキストとして見る**。これで解決する場面は、実はかなり多いはずです。

- `<html` `<table` で始まる → HTML
- `PK` で始まる → ZIP（新しい Excel `.xlsx` はこれ）
- `%PDF` で始まる → PDF
- `{` `[` で始まる → JSON
- 読める文字が並んでいる → CSV かテキスト

**数行見るだけで、次にやることが決まります。**

---

## 6. さらに良い発見：ダウンロードすら要らなかった

HTML だと分かったので、`rvest`（HTMLを読むライブラリ）で読めば解決 ── のはずでした。

しかし、その前に **API の応答をもう一度よく見て**、もっと良い方法が見つかりました。

静的表の詳細を返すエンドポイント（`view`）の応答を、全フィールド展開して眺めます。

```r
bps_static_inspect(951)
```

```
=== トップレベル ===
[1] "status" "data-availability" "data"

=== 全フィールド(先頭40) ===
        data.table_id             data.title       data.subj_id
              "951"     "Daily Average..."               "5"
        data.excel                data.table
"https://www.bps.go.id/.../951.xls"   "&lt;table border=..."
                                       ~~~~~~~~~~~~~~~~~~~~
```

**`data.table` というフィールドに、同じHTMLがそのまま入っていました。**

つまり、

- `data.excel` … ファイルのURL（ダウンロードが要る）
- `data.table` … **同じ内容のHTMLが、応答の中に直接入っている**

ファイルを落とす必要がありません。**API の応答だけで完結します。**

### これがなぜ良いか

3つあります。

1. **通信が1回で済む**（一覧 → ファイルURL → ダウンロード、の3段が2段になる）
2. **ダウンロード先のディレクトリを用意しなくていい**（一時ファイルが散らからない）
3. **ファイルのURLが変わっても壊れない**

3番目が地味に大きい。ファイルURLは、BPS がサイトの構成を変えると変わります。応答の中に入っているデータを使えば、その影響を受けません。

### どうやって見つけたか

`bps_static_inspect()` という関数を作ったからです。やっていることは単純で、**応答を全部展開して並べる**だけです。

```r
#' 静的表のレスポンスの中身を人間が読める形で表示する
#' URLらしき文字列を全部拾って出すので、どのフィールドにファイルがあるか分かる
bps_static_inspect <- function(id, domain = "0000", lang = "eng") {
  res <- bps_static_view(id, domain, lang)

  cat("=== トップレベル ===\n"); print(names(res))
  cat("\nstatus:", as.character(res$status), "\n")

  flat <- unlist(res, use.names = TRUE)
  cat("\n=== 全フィールド(先頭40) ===\n")
  print(utils::head(flat, 40))

  hits <- flat[grepl("^https?://|\\.xlsx?$", flat)]
  if (length(hits)) {
    cat("\n=== URL / ファイルらしきもの ===\n")
    print(hits)
  }
  invisible(res)
}
```

もともとは「ファイルのURLがどのフィールドに入っているか」を探すために作りました。**目的は URL 探しだったのに、URL を使わずに済む方法が見つかった**わけです。

[罠04](04-composite-key.md) とまったく同じ構図です。

> **全部並べて見ると、探していたものより良いものが見つかることがある。**

これは3回目です（[罠02](02-bilingual-catalog.md) の「絞り込む前を全部出す」、[罠04](04-composite-key.md) の「生の応答を並べて見る」、そして今回）。**「まず全部出す」は、この連載でいちばん再利用が効いた作法**かもしれません。

---

## 7. 小さな罠：HTMLエンティティを戻す順序

`data.table` に入っているHTMLは、**エスケープされた状態**です。

```
&lt;table border=&quot;1&quot;&gt;
```

`<` が `&lt;`、`"` が `&quot;` に置き換えられています。JSON の中に HTML をそのまま入れると壊れるので、当然の処理です。

これを元に戻す関数を書きました。

```r
# HTMLエンティティを戻す(&amp; は最後に処理する)
.bps_unescape <- function(x) {
  x <- gsub("&lt;",   "<",  x, fixed = TRUE)
  x <- gsub("&gt;",   ">",  x, fixed = TRUE)
  x <- gsub("&quot;", '"',  x, fixed = TRUE)
  x <- gsub("&#39;",  "'",  x, fixed = TRUE)
  x <- gsub("&nbsp;", " ",  x, fixed = TRUE)
  x <- gsub("&amp;",  "&",  x, fixed = TRUE)   # ← 必ず最後
  x
}
```

**`&amp;` を最後に処理する**、という1点だけ注意が要ります。

理由は、**`&amp;` を先に戻すと、他のエンティティが壊れるから**です。

たとえば元データに `&amp;lt;` という文字列があったとします。これは「`&lt;` という文字列そのもの」を表しています。

- `&amp;` を先に戻す → `&lt;` になる → 次の処理で `<` になってしまう（**誤り**）
- `&amp;` を最後に戻す → `&amp;lt;` のまま残り、最後に `&lt;` になる（**正しい**）

[罠06](06-empty-rows.md) と同じ、**順序の問題**です。

> **同じ処理でも、順序が違えば別の答えを出す。**

この連載で2度目に出てきました。そして今回も、**コードを読んでも順序の理由は分かりません**。だからコメントに `(&amp; は最後に処理する)` と1行だけ書いてあります。

---

## 8. ここからが本番 ── 表の形が毎回違う

HTMLとして読めるようになりました。しかし、**本当の困難はここからでした。**

動的表なら、どの表も同じ形で返ってきます。地域・変数・年・期間の4次元です（[罠04](04-composite-key.md)）。**1つのパーサで全部読めます。**

静的表は違います。**人間が見るために作られた表**なので、形が表ごとにバラバラです。

- ヘッダが何行あるか分からない
- タイトル行があったりなかったりする
- 空行が入る
- 州名の列が1列目とは限らない
- **1つの表に、2つの指標が横に並んでいる**ことがある
- 末尾に脚注が付く

「位置を決め打ちして読む」実装は、**最初の1表でしか動きません**。次の表で必ず壊れます。

これは[罠04](04-composite-key.md) の「桁数を決め打ちする」とまったく同じ構図です。**たまたま動くものを書いてはいけない。**

---

## 9. 対処：形を仮定せず、探す

そこで、次のように考えました。

> **どの表にも共通することは何か。**

見比べると、1つだけありました。

> **どこかに、年が横に並んだ行がある。**

これは統計表である以上、ほぼ必ず成り立ちます。そして、**年の行さえ見つかれば、それを基準に他が決まります**。

- 年の行より下 → データ
- 年の行の**1つ上** → 指標グループ（あれば）
- 年が入っている列 → 値の列

### 年の行を探す

```r
# --- 年の行を探す（1960-2035 の4桁が3つ以上並ぶ行）------------------
is_year_row <- apply(m, 1, function(r) {
  d <- .int_of(r)
  sum(!is.na(d) & d >= 1960 & d <= 2035) >= 3
})
hdr <- which(is_year_row)[1]
if (is.na(hdr)) stop("年の行が見つかりません")
```

判定は「1960〜2035の範囲の4桁数値が、**3つ以上**並んでいる行」です。

**なぜ3つ以上か。** 1つや2つなら偶然に一致することがあるからです（表のタイトルに年が入っている、など）。3つ並ぶのは、年のヘッダ行以外にはまず起こりません。

**なぜ1960〜2035か。** 統計の年として現実的な範囲だからです。この上限は将来伸ばす必要がありますが、**範囲を決めておくことで、無関係な4桁数値（人口や金額）を年と誤認しなくなります**。

そして、見つけた結果は**必ず表示します**。

```r
cat("年の行:", hdr, " 年:", paste(range(yrs[ycol]), collapse = "-"),
    " 値の列数:", length(ycol), "\n")
```

```
年の行: 4  年: 2007-2025  値の列数: 38
```

**自動検出した結果が正しいかを、人間が一目で確認できます。** 自動化した処理ほど、結果を見せる必要があります。黙って推測されるのがいちばん怖い。

---

## 10. 1つの表に、2つの指標が横に並んでいる

カロリーの表（静的表951）を開いたとき、想定外の構造に当たりました。

```
行1  Daily Average Consumption ...（タイトル。全列に複製されている）
行2  （空行）
行3  Province | Calories (kkal) x19 | Protein (gram) x19   ← 指標グループ
行4  Province | 2007 ... 2025       | 2007 ... 2025        ← 年
行5〜 Aceh    | 2 210.02 ...        | 61.19 ...            ← データ
```

**1つの表に、カロリーとタンパク質が横に並んでいます。**

年の行だけを見ると、`2007` が**2回**出てきます。左半分がカロリーの2007年、右半分がタンパク質の2007年です。

**年だけでは区別できません。** その1つ上の行（指標グループ）と組にして、初めて意味が決まります。

### 対処

指標グループ行のキーワードと、指標名の対応を外から渡せるようにしました。

```r
if (!is.null(group_map)) {
  if (hdr < 2) stop("グループ行がありません")
  grp <- as.character(unlist(m[hdr - 1, ]))
  ind <- rep(NA_character_, ncol(m))
  for (k in names(group_map)) {
    ind[grepl(k, grp, ignore.case = TRUE)] <- group_map[[k]]
  }
}
```

呼び出す側は、こう書きます。

```r
parse_static_long(tb, group_map = c("Calor"   = "mean_calories",
                                    "Protein" = "mean_protein"))
```

**`"Calor"` と部分一致で書いている**のは、実際のラベルが `Calories (kkal)` なのか `Calorie` なのか、表によって揺れるからです。完全一致にすると、たった一文字の違いで落ちます。

そして、割り当て結果を**必ず表示します**。

```r
cat("指標ごとの列数:\n")
print(table(ind[ycol], useNA = "ifany"))
```

```
mean_calories  mean_protein
           19            19
```

**19列ずつ、きれいに割れました。** もし片方が0なら、キーワードが当たっていないと即座に分かります。

---

## 11. 数値の書式と、州名の改行

読めるようになったあとも、細かい問題が2つありました。

### 桁区切りが「空白」

```
2 210.02
```

これは「2210.02」です。**カンマではなく空白**が桁区切りに使われています。国際的な表記（SI）としては正しいのですが、素直に `as.numeric()` に渡すと NA になります。

対処は、**数字と小数点とマイナス以外を全部落とす**ことにしました。

```r
# 桁区切りの空白・改行・記号を落として数値にする
.num_of <- function(x) {
  z <- gsub("[^0-9.-]", "", as.character(x))
  z[z %in% c("", "-", ".", "--")] <- NA_character_
  suppressWarnings(as.numeric(z))
}
```

空白だけでなく、カンマ、改行、通貨記号も一度に落ちます。**「何を除くか」を列挙するより、「何を残すか」を列挙するほうが安全**です。除くもののリストは、必ず漏れます。

`z %in% c("", "-", ".", "--")` の行は、**除去した結果が数値にならないもの**を明示的に NA にしています。統計表で欠測を表す `-` や `...` が、これで正しく NA になります。

### 州名に改行が入る

HTMLの表では、セルの中で折り返しが起きます。

```
Sumatera
  Utara
```

これをそのまま州名として使うと、`Sumatera\n  Utara` という名前になり、他のデータと結合できません。

`stringr::str_squish()` を通すだけで解決します。

```r
prov_raw <- str_squish(body[[prov_col]])          # 改行もここで潰れる
```

`str_squish()` は「前後の空白を落とし、連続する空白を1つにまとめる」関数です。改行も空白の一種なので、これで潰れます。

**この手の問題は、HTMLから表を読むときには必ず起きます。** 最初から通しておくのが安全です。

---

## 12. 脚注が、州として混入する

最後の問題です。

パースした結果を確認すると、**州の数が合いませんでした**。33州や38州のはずが、**35や39**になっています。

原因を探すと、表の末尾にこんな行がありました。

```
1) Data Still Joins East Kalimantan Province
```

**脚注です。** 「（この地域の）データは、まだ東カリマンタン州に含まれています」という注記です。

表の中では普通の行として存在するので、州名の列に脚注の文章が入り、値の列に脚注番号の `1` が入ります。**「名前が "1) Data Still Joins..." で、値が 1.00 の州」**ができあがるわけです。

### 対処：州名のホワイトリスト

ここで使ったのは、**すでに持っている知識**です。

インドネシアの州の名前は、**分かっています**。33州、34州、38州のいずれかで、名前の一覧は手元にあります（[罠09](README.md) で作ります）。

だったら、**その一覧に無いものは州ではない**。

```r
# --- 州名として妥当か -------------------------------------------------
# 静的表の末尾には脚注行が付く。実例:
#   "1) Data Still Joins East Kalimantan Province"
# これが州として混入し、値 1.00（脚注番号）を持つ行になっていた。
# 州名の集合は分かっているので、そこに無いものは落として報告する。
if (is.null(valid_names)) valid_names <- PROV38
bad <- setdiff(unique(out$prov_name), valid_names)
if (length(bad) > 0) {
  cat("[!] 州名として認識できない行を落としました（脚注などのはず）:\n")
  for (b in bad) cat("   ", b, "\n")
  out <- filter(out, prov_name %in% valid_names)
}
```

**落とすだけでなく、落としたものを必ず表示します。** これが重要です。

もし黙って落としていたら、**本物の州が表記ゆれで落ちても気づけません**。実際、この表示のおかげで「`Kalimantan Utara 1)`（脚注番号つきの州名）」という別の問題が見つかりました（[罠08](README.md) で扱います）。

> **除外は、除外したものを見せてはじめて安全になる。**

これは[罠02](02-bilingual-catalog.md) の「絞り込む前と後の両方を出す」と同じ原則です。**捨てるものを見せる。**

---

## 13. 直ったことをどう確かめたか

### 確認その1：自動検出の結果が妥当か

```
年の行: 4  年: 2007-2025  値の列数: 38
指標ごとの列数:
mean_calories  mean_protein
           19            19
```

- 年の行が4行目 → 表の構造と一致
- 2007〜2025年 → 19年分。`19 × 2指標 = 38列` で計算が合う
- 指標ごとに19列ずつ → きれいに割れている

**すべての数字が掛け算で説明できます。**

### 確認その2：州数が正しいか

```
=== check_panel ===
   year n_prov n_rows
1  2007     33     33
...
19 2025     33     33
```

33州、行数も33。**脚注は除外され、重複もありません。**

### 確認その3：値が妥当な範囲か

カロリー摂取量は、1人1日あたり2,000kcal前後のはずです。

```
2007年 全国加重平均: 1,932 kcal
2018年 全国加重平均: 2,153 kcal
```

**妥当な範囲です。** もし桁区切りの処理を間違えていれば、`2 210.02` が `2` になったり `221002` になったりして、この検算で一発で分かります。

### 確認その4：もう1つの静的表でも動くか

いちばん大事な確認です。**別の表で試します。**

都市人口比率の表（静的表1276）を、`group_map = NULL`（指標は1つ）で読ませました。

```
年の行: 3  年: 2010-2035  値の列数: 6
```

**読めました。** 年の行の位置（3行目）も、値の列数（6列＝5年刻み）も、カロリー表とはまったく違います。それでも**同じコードで読めています**。

形を仮定していないので、形が違っても動く。**これが「たまたま動く」との違い**です。

（なお、この表は2030年・2035年という**将来推計**を含んでいたので、`year <= 2025` で切りました。「取れたものを全部使う」のではなく、**何を使うかは別途決める**必要があります。）

---

## 14. あなたのAPIでも同じことが起きる

### 「拡張子と中身が違う」はよくある

| 実際に見かける形 | 中身 |
|---|---|
| `.xls` | HTML の `<table>` |
| `.xls` | タブ区切りテキスト |
| `.csv` | セミコロン区切り（欧州系） |
| `.xlsx` | ZIP（正常。ただし古いライブラリは読めない） |
| `.txt` | 固定長レコード |
| `.json` | JSON Lines（1行1オブジェクト） |

**先頭数行を見れば、どれか分かります。**

### 「人間向けの表」を機械で読むときの原則

政府統計や企業のレポートは、**人間が見るために作られています**。だから、

- 見出しが複数行にまたがる
- セルが結合されている
- 小計・合計が混ざる（→ [罠05](05-derived-dimensions.md)）
- 脚注が表の中にある
- 単位が見出しに書いてある

これらは「汚いデータ」ではなく、**紙のレイアウトとして正しい**のです。機械で読むには変換が要る、というだけです。

原則は2つです。

> **位置を決め打ちせず、目印を探す。**（年の行、ヘッダのキーワード）

> **知っている集合と照合する。**（州名の一覧、想定される値の範囲）

### 日本の統計でも同じ

e-Stat のダウンロードファイルも、同じ性格を持っています。

- ヘッダが3〜5行にわたる
- 「全国」「〇〇県計」が混ざる
- 秘匿値が `X` や `-` で入る
- 表によって列の構成が違う

**「年の行を探す」に相当する目印**を、その表なりに見つけるのが第一歩です。

---

## 15. チェックリスト

### ファイルが読めないとき

- [ ] **先頭数行をテキストとして表示したか**（これが最初）
- [ ] 拡張子と中身が一致しているか
- [ ] ダウンロードせずに済む経路はないか（応答の中に入っていないか）
- [ ] 文字コードは適切か

### 人間向けの表を読むとき

- [ ] ヘッダの位置を**決め打ちしていない**か
- [ ] 何を目印にしているか、はっきりしているか
- [ ] **自動検出した結果を、画面に出しているか**
- [ ] 1つの表に複数の指標が入っていないか
- [ ] 数値の桁区切りは何か（カンマ／空白／ピリオド）
- [ ] セル内に改行が入っていないか

### 行を選別するとき

- [ ] **既知の集合（州名など）と照合しているか**
- [ ] **落とした行を表示しているか**
- [ ] 脚注・小計・合計が混ざっていないか

### 別の表でも試したか

- [ ] **形の違う表を、少なくとも1つ**同じコードで読んだか

---

## 16. まとめ

### 何が起きたか

「Excel」と称するファイルの中身が **HTML** でした。`readxl` は「開けません」としか言わず、原因は分かりません。先頭数行をテキストとして見て、初めて判明しました。

さらに、応答を全フィールド展開したところ、**同じHTMLが `data$table` に直接入っていた**ので、ダウンロード自体が不要になりました。

そのあとが本番で、**静的表は形が表ごとにバラバラ**でした。位置を決め打ちすると1表でしか動きません。

### どう直したか

1. **中身を見て**、HTMLだと判定した
2. 応答を**全フィールド展開**して、より良い経路（`data$table`）を見つけた
3. **形を仮定せず、「年が3つ以上並んだ行」を目印に探す**パーサを書いた
4. 1つの表に2指標が並ぶ構造に、**指標グループ行**で対応した
5. 桁区切りの空白、セル内改行を正規化した
6. **州名のホワイトリスト**で脚注行を除外し、**除外したものを表示**した

### 一般化した教訓

> **ファイルの種類は、拡張子でも提供元の説明でもなく、中身で決まる。**
> 読めないときは、まず先頭数行をテキストで見る。

> **位置を決め打ちせず、目印を探す。**
> [罠04](04-composite-key.md) の「桁数を決め打ちしない」と同じ原則。

> **除外は、除外したものを見せてはじめて安全になる。**

### 生成AIとの協働という観点から

この罠で効いたのは、**「まず全部出す」という作法**でした。この連載で3回目の登場です。

| 回 | 何を全部出したか | 何が見つかったか |
|---|---|---|
| [罠02](02-bilingual-catalog.md) | 絞り込む前の候補28件 | インドネシア語の表題 |
| [罠04](04-composite-key.md) | 生のJSON応答 | キーを組み立てる設計 |
| **罠07** | 応答の全フィールド | **ダウンロード不要の経路** |

3回とも、**探していたものとは違うものが見つかりました**。

生成AIとの作業では、目的に最短で向かうコードがすぐ出てきます。それは強みですが、**寄り道の途中で見つかるものが減る**という側面もあります。「全部出す」は、その寄り道を意図的に作る作法だったのだと思います。

コストは `print()` 1行です。**払う価値のある1行**でした。

---

## 付録A：コード全文

```r
# =====================================================================
# 静的表を読む
# =====================================================================

# --- URL のスラッグを解く --------------------------------------------
#' @examples bps_decode_slug("MTg4NiMy")   # "1886#2" → 動的表 1886
#'           bps_decode_slug("OTQ1IzE=")   # "945#1"  → 静的表 945
bps_decode_slug <- function(s) {
  s <- gsub("=+$", "", s)
  pad <- (4 - nchar(s) %% 4) %% 4        # パディングを足し直す
  s <- paste0(s, strrep("=", pad))
  txt <- rawToChar(jsonlite::base64_dec(s))
  parts <- strsplit(txt, "#", fixed = TRUE)[[1]]
  list(id   = parts[1],
       type = if (length(parts) > 1) parts[2] else NA_character_,
       kind = if (length(parts) > 1 && parts[2] == "1") "statictable" else "var")
}

# --- 応答を全部並べて見る（探索用）-----------------------------------
bps_static_inspect <- function(id, domain = "0000", lang = "eng") {
  res <- bps_static_view(id, domain, lang)
  cat("=== トップレベル ===\n"); print(names(res))
  cat("\nstatus:", as.character(res$status), "\n")
  flat <- unlist(res, use.names = TRUE)
  cat("\n=== 全フィールド(先頭40) ===\n"); print(utils::head(flat, 40))
  hits <- flat[grepl("^https?://|\\.xlsx?$", flat)]
  if (length(hits)) { cat("\n=== URL / ファイルらしきもの ===\n"); print(hits) }
  invisible(res)
}

# --- HTMLエンティティを戻す（&amp; は最後）----------------------------
.bps_unescape <- function(x) {
  x <- gsub("&lt;",   "<",  x, fixed = TRUE)
  x <- gsub("&gt;",   ">",  x, fixed = TRUE)
  x <- gsub("&quot;", '"',  x, fixed = TRUE)
  x <- gsub("&#39;",  "'",  x, fixed = TRUE)
  x <- gsub("&nbsp;", " ",  x, fixed = TRUE)
  x <- gsub("&amp;",  "&",  x, fixed = TRUE)   # ← 必ず最後
  x
}

#' 静的表の中身を data.frame として取り出す
#'
#' BPS の静的表は「Excel」と言いつつ中身は HTML の表で、しかも同じものが
#' レスポンスの data$table にエスケープされた状態で入っている。
#' ダウンロードせずにここから直接読める。
bps_static_table <- function(id, domain = "0000", lang = "eng") {
  if (!requireNamespace("rvest", quietly = TRUE))
    stop("install.packages('rvest') が必要です")

  res <- bps_static_view(id, domain, lang)
  if (!identical(res$status, "OK")) stop("status=", as.character(res$status))

  html <- res$data$table
  if (is.null(html) || !nzchar(html)) stop("data$table が空です")

  doc <- rvest::read_html(.bps_unescape(html))
  tbl <- rvest::html_table(doc, fill = TRUE)
  cat("表の数:", length(tbl), "\n")
  for (i in seq_along(tbl))
    cat("  [", i, "] ", nrow(tbl[[i]]), "行 x ", ncol(tbl[[i]]), "列\n", sep = "")
  tbl
}

# --- 数値と整数の取り出し --------------------------------------------
.int_of <- function(x) suppressWarnings(as.integer(gsub("[^0-9]", "", x)))

# 桁区切りの空白・改行・記号を落として数値にする
# 「何を除くか」ではなく「何を残すか」で書く（除くもののリストは必ず漏れる）
.num_of <- function(x) {
  z <- gsub("[^0-9.-]", "", as.character(x))
  z[z %in% c("", "-", ".", "--")] <- NA_character_
  suppressWarnings(as.numeric(z))
}

#' 静的表を「州 × 指標 × 年」の縦長に開く
#'
#' 静的表は構造がバラバラなので、位置決め打ちでは壊れる。
#' 共通しているのは「どこかに年が並んだ行がある」ことだけなので、
#' **年の行を探して、そこを基準に読む**。
#'
#' @param group_map 指標グループ行のキーワード → 指標名 の対応。
#'                  例 c("Calor" = "mean_calories", "Protein" = "mean_protein")
#'                  NULL なら指標は1つとみなす
parse_static_long <- function(tb, group_map = NULL,
                              indicator = "value", prov_col = 1,
                              valid_names = NULL) {

  m <- as.data.frame(tb, stringsAsFactors = FALSE)

  # --- 年の行を探す（1960-2035 の4桁が3つ以上並ぶ行）------------------
  # 3つ以上にするのは、偶然の一致を避けるため。
  is_year_row <- apply(m, 1, function(r) {
    d <- .int_of(r)
    sum(!is.na(d) & d >= 1960 & d <= 2035) >= 3
  })
  hdr <- which(is_year_row)[1]
  if (is.na(hdr)) stop("年の行が見つかりません")

  yrs  <- .int_of(unlist(m[hdr, ]))
  ycol <- which(!is.na(yrs) & yrs >= 1960 & yrs <= 2035)

  # --- 指標グループ行（年の行の1つ上）---------------------------------
  # 1つの表に2指標が横並びのことがある（カロリー表 951）。
  # 年だけでは区別できないので、1つ上の行と組にする。
  if (!is.null(group_map)) {
    if (hdr < 2) stop("グループ行がありません")
    grp <- as.character(unlist(m[hdr - 1, ]))
    ind <- rep(NA_character_, ncol(m))
    for (k in names(group_map)) {
      ind[grepl(k, grp, ignore.case = TRUE)] <- group_map[[k]]
    }
  } else {
    ind <- rep(indicator, ncol(m))
  }

  # 自動検出した結果は必ず見せる
  cat("年の行:", hdr, " 年:", paste(range(yrs[ycol]), collapse = "-"),
      " 値の列数:", length(ycol), "\n")
  if (!is.null(group_map)) {
    cat("指標ごとの列数:\n")
    print(table(ind[ycol], useNA = "ifany"))
  }

  keep <- ycol[!is.na(ind[ycol])]
  if (length(keep) == 0) stop("group_map がどの列にも当たりません")

  body <- m[(hdr + 1):nrow(m), , drop = FALSE]
  prov_raw <- str_squish(body[[prov_col]])          # セル内改行もここで潰れる

  ok <- nzchar(prov_raw) & !is_national(prov_raw)
  body <- body[ok, , drop = FALSE]
  prov_raw <- prov_raw[ok]

  out <- bind_rows(lapply(keep, function(j) {
    data.frame(prov_name = normalize_prov(prov_raw),
               indicator = ind[j],
               year      = yrs[j],
               value     = .num_of(body[[j]]),
               stringsAsFactors = FALSE)
  }))

  out <- out |> filter(!is.na(value))

  # --- 州名として妥当か（脚注行の除去）--------------------------------
  # 実例: "1) Data Still Joins East Kalimantan Province" が
  #       値 1.00 を持つ「州」として混入していた。
  # 落とすだけでなく、落としたものを必ず表示する。
  # （本物の州が表記ゆれで落ちたときに気づけるようにするため）
  if (is.null(valid_names)) valid_names <- PROV38
  bad <- setdiff(unique(out$prov_name), valid_names)
  if (length(bad) > 0) {
    cat("[!] 州名として認識できない行を落としました（脚注などのはず）:\n")
    for (b in bad) cat("   ", b, "\n")
    out <- filter(out, prov_name %in% valid_names)
  }

  out <- out |> arrange(indicator, year, prov_name)

  # 重複ガード（動的表側と同じ考え方 → 罠05）
  dup <- out |> count(prov_name, indicator, year) |> filter(n > 1)
  if (nrow(dup) > 0) {
    cat("[!] 1州×1指標×1年に複数行があります（先頭10件）:\n")
    print(as.data.frame(head(dup, 10)))
    stop("重複があります。group_map と列の対応を確認してください。")
  }

  out
}
```

### 使い方

```r
# 1. まず形を見る（いきなりパースしない）
tbl <- bps_static_table(951)
#> 表の数: 1
#>   [ 1 ] 40行 x 39列

m <- as.data.frame(tbl[[1]])
print(m[1:6, 1:6])          # 先頭を目で見る

# 2. 形が分かってからパースする
cal <- parse_static_long(tbl[[1]],
                         group_map = c("Calor"   = "mean_calories",
                                       "Protein" = "mean_protein"))
#> 年の行: 4  年: 2007-2025  値の列数: 38
#> 指標ごとの列数:
#> mean_calories  mean_protein
#>            19            19

# 3. 検算
print(as.data.frame(check_panel(cal)))
```

---

## 付録B：よくある質問

### Q1. なぜ最初から `rvest` で読まなかったのですか？

**HTMLだと知らなかったからです。** フィールド名が `excel` で、拡張子が `.xls` だったので、Excel だと思うのが自然です。

この罠の本質はそこで、**「名前が中身を保証しない」**という一点に尽きます。

### Q2. 「年の行を探す」方法が使えない表はありますか？

あります。たとえば、

- 年が**縦**に並んでいる表（行が年、列が地域）
- 年が「令和6年度」のような表記の表
- 年の代わりに「第1四半期」などが並ぶ表

その場合は、別の目印を探すことになります。**大事なのは「年の行を探す」という具体的手法ではなく、「位置を決め打ちせず目印を探す」という考え方**です。

なお、年が縦に並ぶ表なら、**転置してから同じ関数に渡す**という手もあります。

### Q3. 脚注を落とすとき、本物の州が落ちる心配はありませんか？

あります。だから**落としたものを必ず表示**しています。

実際、この表示のおかげで `Kalimantan Utara 1)`（脚注番号が名前に付いた州）が見つかりました。これは本物の州なので、落としてはいけません。[罠08](README.md) で、脚注記号を名前から取り除く処理を入れることになります。

**「落として表示する」なら回復できますが、「黙って落とす」と永久に気づけません。**

### Q4. 他の罠も知りたいのですが

この記事は連載の7本目です。

1. [一覧APIの暗黙の打ち切り](01-silent-truncation.md)
2. [カタログの二言語混在](02-bilingual-catalog.md)
3. [年の必須指定と3年上限](03-year-parameter.md)
4. [連結キーの桁数不定](04-composite-key.md)
5. [派生変数・期間の未指定](05-derived-dimensions.md)
6. [行は存在するが値が空](06-empty-rows.md)
7. **静的表の実体がHTML**（この記事）
8. 州名の表記ゆれと脚注記号 ── 地図の一部が灰色になる
9. 行政区画の変更（33→34→38州） ── 足せる量と足せない量
10. 公表基準の断絶（3月調査と9月調査） ── 検算が失敗したとき、何を疑うか

---

## この記事について

この記事は、日本計算機統計学会シンポジウムでの報告「検算駆動による生成AIとの協働 ── インドネシア公的統計WebAPIからの州別パネル構築とShinyによる可視化」の補足資料として作成しました。

本文中のコード、出力、数値は、すべて実際の作業記録に基づいています。うまくいかなかった過程も、そのまま残しています。

### 生成AIの利用について

**本記事の文章は、生成AI（Claude Opus 5、推論設定「高」）が、久保田による指示（プロンプト）と複数回のやりとりを経て生成したものです。** 構成・記述・コード解説はAIによる出力であり、掲載しているコード、コンソール出力、数値は、いずれも実際の作業記録に基づいています。内容は著者が確認したうえで公開しています。

この記事の主題そのものが「生成AIと協働してデータを取得した記録」であるため、記事の生成過程を隠す理由がありません。念のため明記しておきます。

- 著者：久保田貴文（多摩大学）
- 連絡先：kubota@tama.ac.jp
- Web：https://takafumikubota.jp/

この作業で用いた統計は、インドネシア中央統計庁（BPS）が公開するWebAPIから取得しました。
Layanan ini menggunakan API Badan Pusat Statistik (BPS).
（本サービスはインドネシア中央統計庁のAPIを使用しています。）
